from game.defenses.firewall import Firewall
from game.defenses.antivirus import Antivirus
from game.defenses.ids import IntrusionDetectionSystem
from game.defenses.mfa import MultiFactorAuthentication
from game.defenses.ai_anomaly import AIAnomalyDetection
from game.defenses.incident_response import IncidentResponsePlan
from game.defenses.siem import SIEM
from game.defenses.segmentation import NetworkSegmentation
from game.defenses.deception import DeceptionTechnology